//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDExcellent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddArticle
    {
        public int Id { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Title { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
