//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDExcellent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddNewUser
    {
        public string Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public int Title { get; set; }
        public string Area { get; set; }
        public int ReportTo { get; set; }
        public int Status { get; set; }
    }
}
