//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDExcellent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTask
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Create_by { get; set; }
        public string Description { get; set; }
        public string ChooseCalendar { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
