//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDExcellent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatePlanVisit
    {
        public int PlanId { get; set; }
        public System.DateTime Time { get; set; }
        public int Distributor { get; set; }
        public string Purpose { get; set; }
        public string Guest { get; set; }
    }
}
