//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDExcellent.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDExcellentEntities1 : DbContext
    {
        public CDExcellentEntities1()
            : base("name=CDExcellentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AddArea> AddAreas { get; set; }
        public virtual DbSet<AddArticle> AddArticles { get; set; }
        public virtual DbSet<AddDistributor> AddDistributors { get; set; }
        public virtual DbSet<AddNewUser> AddNewUsers { get; set; }
        public virtual DbSet<AddQuestionnaire> AddQuestionnaires { get; set; }
        public virtual DbSet<CreateNotification> CreateNotifications { get; set; }
        public virtual DbSet<CreatePlanVisit> CreatePlanVisits { get; set; }
        public virtual DbSet<CreateTask> CreateTasks { get; set; }
        public virtual DbSet<RequestSurvey> RequestSurveys { get; set; }
        public virtual DbSet<TaskDetail> TaskDetails { get; set; }
        public virtual DbSet<VisitPlanDetail> VisitPlanDetails { get; set; }
    }
}
